#!/bin/bash

if [ "$(uname)" != "Darwin" ]; then
 exit
fi

if [ -x "$(command -v brew)" ]; then
  echo "Already have brew"
  exit
fi

echo "Installing brew"
cd ~ || exit
mkdir .brew && curl -L https://github.com/Homebrew/brew/tarball/master \
  | tar xz --strip 1 -C .brew

echo "Updating brew packages"
~/.brew/bin/brew update
