#!/bin/bash

if [ -x "$(command -v cmake)" ]; then
  echo "Already have cmake"
  exit
fi

if [ "$(uname)" == "Darwin" ]; then
  echo "Installing cmake from brew"
  brew install cmake
else
  echo "Installing cmake from apt"
  sudo apt install cmake
fi
