#!/bin/bash

if [ -x "$(command -v go)" ]; then
  echo "Already have go"
  exit
fi

if [ "$(uname)" == "Darwin" ]; then
  echo "Installing go from brew"
  brew install go
else
  echo "Installing go from apt"
  sudo apt install golang
fi
