#!/bin/bash

# Check for python devel. Adapted from http://stackoverflow.com/a/4850603
IMPORT="from distutils import sysconfig as s"
CHECK_CONFIG="print s.get_config_vars()['INCLUDEPY']"
INCLUDE_PY=$(python -c "$IMPORT; $CHECK_CONFIG")
if [ -f "${INCLUDE_PY}/Python.h" ]; then
  echo "Already have python devel"
  exit
fi

if [ "$(uname)" == "Darwin" ]; then
  echo "WARNING python devel NOT INSTALLED"
else
  echo "Installing python-dev from apt"
  sudo apt install python-dev
fi
