#!/bin/bash

if [ -x "$(command -v curl)" ]; then
  echo "Already have curl"
  exit
fi

if [ "$(uname)" == "Darwin" ]; then
  echo "Installing curl from brew"
  brew install curl
else
  echo "Installing curl from apt"
  sudo apt install curl
fi
