#!/bin/bash

if [ -x "$(command -v jq)" ]; then
  echo "Already have jq"
  exit
fi

if [ "$(uname)" == "Darwin" ]; then
  echo "Installing jq from brew"
  ~/.brew/bin/brew install jq
else
  echo "Installing jq from apt"
  sudo apt install jq
fi

