#!/bin/bash

if [ -x "$(command -v ag)" ]; then
  echo "Already have ag"
  exit
fi

if [ "$(uname)" == "Darwin" ]; then
  echo "Installing ag from brew"
  ~/.brew/bin/brew install ag
else
  echo "Installing ag from apt"
  sudo apt install silversearcher-ag
fi
