#!/bin/bash

if [ -x "$(command -v dart)" ]; then
  echo "Already have dart"
  exit
fi

if [ "$(uname)" == "Darwin" ]; then
  echo "Installing dart from brew"
  brew tap dart-lang/dart
  brew install dart --with-dartium --devel
else
  echo "Downloading latest dart"
  DOWNLOAD="https://storage.googleapis.com/dart-archive/channels/dev/release/"
  LATEST="latest/sdk/dartsdk-linux-x64-release.zip"
  wget $DOWNLOAD$LATEST -O /tmp/dart-release.zip
  unzip -qo /tmp/dart-release.zip -d ~
fi
