#!/bin/bash

if [ -d "$HOME/.fonts" ]; then
  echo "Already have fonts"
  exit
fi

roman="2.030R-ro"
italic="1.050R-it"
font="source-code-pro"

download="https://github.com/adobe-fonts/$font/archive/$roman/$italic.zip"
file="$italic.zip"
directory="${font}-${roman}-${italic}"

if [ "$(uname)" == "Darwin" ]; then
  echo "Installing source-code-pro from brew"
  ~/.brew/bin/brew tap caskroom/fonts
  ~/.brew/bin/brew cask install font-source-code-pro
  mkdir -p ~/.fonts
else
  echo "Downloading source-code-pro"
  mkdir /tmp/font
  cd /tmp/font || exit
  wget "$download"
  unzip "$file"
  mkdir -p ~/.fonts
  cp $directory/OTF/*.otf ~/.fonts/
  fc-cache -f -v
fi
