#!/bin/bash

if [ -x "$(command -v rvm)" ]; then
  echo "Already have rvm"
  exit
fi

if [ "$(uname)" == "Darwin" ] && [ ! -x "$(command -v gpg)" ]; then
  echo "Installing gpg"
  brew install gpg
fi

echo "Adding rvm gpg key"
gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
echo "Running rvm install script"
curl -sSL https://get.rvm.io | bash -s -- --ignore-dotfiles
