#!/bin/bash

if [ -x "$(command -v tmux)" ]; then
  echo "Already have tmux"
  #TODO need to check for recent version?
  exit
fi

if [ "$(uname)" == "Darwin" ]; then
  brew install tmux
else
  echo "Installing libevent-dev from apt"
  sudo apt install libevent-dev
  echo "Installing libcurses-dev from apt"
  sudo apt install libncurses-dev
  echo "Downloading tmux 2.2"
  wget https://github.com/tmux/tmux/releases/download/2.2/tmux-2.2.tar.gz \
    -O /tmp/tmux.tar.gz
  cd /tmp || exit
  echo "Extracting tmux"
  tar -xzf tmux.tar.gz
  cd tmux-2.2 || exit
  echo "Installing tmux"
  ./configure && make && sudo make install
fi
