#!/bin/bash

if [ -x "$(command -v tmux)" ]; then
  if [ "$(echo "$(tmux -V | cut -c 6-) >= 2.6" | bc)" = 1 ]; then
    echo "Already have tmux"
    exit
  fi
  echo "Upgrading tmux"
fi

if [ "$(uname)" == "Darwin" ]; then
  ~/.brew/bin/brew install tmux
else
  echo "Installing libevent-dev from apt"
  sudo apt install libevent-dev
  echo "Installing libcurses-dev from apt"
  sudo apt install libncurses-dev
  echo "Downloading tmux 2.6"
  wget https://github.com/tmux/tmux/releases/download/2.6/tmux-2.6.tar.gz \
    -O /tmp/tmux.tar.gz
  cd /tmp || exit
  echo "Extracting tmux"
  tar -xzf tmux.tar.gz
  cd tmux-2.6 || exit
  echo "Installing tmux"
  ./configure && make && sudo make install
fi
