#!/bin/bash

if [ -x "$(command -v vim)" ]; then
  # Look for vim 8.1
  VERSION=$(vim --version | sed -n 's/VIM - Vi IMproved \([0-9\.]\+\) .*/\1/p')

  if [ "$VERSION" == "8.1" ]; then
    echo "Already have vim 8.1"
    exit
  fi
fi

if [ "$(uname)" == "Darwin" ]; then
  echo "Installing vim from brew"
  # Will try to install perl as a dependency, which will fail unless berkeley-db
  # is installed first.
  # https://stackoverflow.com/a/46660972/374798
  ~/.brew/bin/brew install berkeley-db
  ~/.brew/bin/brew install vim
else
  echo "Installing vim from apt"
  sudo apt-get install vim-nox
fi

echo "Installing vim plugins"
vim +PlugInstall +qall
