#!/bin/bash

if [[ "$SHELL" =~ .*zsh.* ]]; then
  echo "Already using zsh"
  exit
fi

if [ ! -x "$(command -v zsh)" ]; then
  if [ "$(uname)" == "Darwin" ]; then
    echo "Installing zsh from brew"
    brew install zsh
  else
    echo "Installing zsh from apt"
    sudo apt install zsh
  fi
fi

echo "Setting default shell"
chsh -s "$(which zsh)"
