.TH "git-gud" 1 "April 2018" "git-gud 0.1.0" "git-gud - git pull and remove branches deleted from the remote"

.SH NAME
git-gud - git pull and remove branches deleted from the remote

.SH DESCRIPTION
git-gud - git pull and remove branches deleted from the remote. Any local
branches that match branches which were deleted from the remote will be deleted
even if they have unmerged changes.
