.TH "git-gud" 1

.SH NAME
git-gud - git pull and remove branches deleted from the remote

.SH DESCRIPTION
git-gud - git pull and remove branches deleted from the remote. Any local
branches that match branches which were deleted from the remote will be deleted
even if they have unmerged changes. Always moves to the default branch.

If there is a remote named "upstream" it is fetched as well and the default
branch on the upstream is merged with --ff-only into the local default branch,
then pushed.
