.TH "git-squash" 1 "March 2018" "git-squash 0.1.0" "git-squash - squash all commits since the upstream branch"

.SH NAME
git-squash - squash all commits since the upstream branch

.SH SYNOPSIS
git-squash <ref>

.SH DESCRIPTION
git\-squash \- squash all commits since <ref>. By default uses the upstream
branch (same behavior as git rebase -i).

Updates all choices for commits from "pick" to "squash" then opens an editor to
update the commit message.
