.TH "git-start" 1

.SH NAME
git-start - start a new feature branch from the current branch

.SH DESCRIPTION
git-start - start a new named feature branch and set the upstream to the current
branch. If the current branch is is "master" and has commits that are not pushed
to a tracked remote, those commits will be moved to the new branch and removed
from master.
