.TH "git-pr" 1 "March 2018" "git-pr 0.1.0" "git-pr - creates a branch for a pull request from github"

.SH NAME
git-pr - creates a branch for a pull request from github

.SH SYNOPSIS
git-pr [-r <remote>] <pr number>

.SH DESCRIPTION
git\-pr \- creates a branch for a pull request from github. This is handy if the
pull request was made from a github repo which is not already set as a remote.

.SH OPTIONS
.TP
.B "-r"
The remote which points to the github repo. By default "origin"
.TP
.B "-h"
Print help
